#!/usr/bin/env bash

docker run --rm -v $(pwd):/tmp -w /tmp brownout bash -c 'm68k-ataribrowner-elf-g++ -std=c++1z -O3 -Iinclude -Iinclude/common -Iinclude/modules -c src/main.cpp -o main.o && m68k-ataribrowner-elf-objdump -d main.o' && cp main.o ~/Documents/FS-UAE/Hard\ Drives/development/
